### ISSUE TITLE
如何便以为so动态库

### ISSUE THREAD

**Issue by appdev** [jkkj93/FREYA-LIVE-LIBRARY-OPTIMIZER-FOR-ANDROID#2]
使用脚本后编译的全是.a的静态库，导致包很大，如何修改让其编译成动态库呢？

**Comment by jkkj93** [comment]
FREYA-LIVE-LIBRARY-OPTIMIZER-FOR-ANDROID编译出的.a静态库只作为开发使用。发布时是不需要带上的，只需要带上在静态库基础上开发，并编译生成的so库即可。
另外如果最终编译生成的so文件没有经过strip，那么体积也会比较大。只需到编译目录的libs目录找到strip后的so文件即可，而不要去obj目录中找。同时也可以用ndk提供的工具手动strip。

**Comment by appdev** [comment]
好的，谢谢。

**Comment by jkkj93** [comment]
不客气
